config/routes.rb
Rails.application.routes.draw do

resources :messages

root 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def index
		@messages = Message.all.order("created_at DESC")
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)
		if @message.save
			redirect_to '/', notice: "Brawo, wiadomość dodana!"
		else
			render 'new'
		end
	end

	def show
		@message = Message.find(params[:id])
	end

	def edit
		@message = Message.find(params[:id])
	end

	def update
		if @message.update(message_params)
			redirect_to '/', notice: "Wiadomość zmieniona!"
		else
			render 'edit'
		end
	end

	def destroy
		@message = Message.find(params[:id])
		@message.destroy
		redirect_to root_path, notice: "Wiadomość usunięta!"
	end

	private

	def message_params
		params.require(:message).permit(:title, :content)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/edit.html.erb
<%= form_for(@message) do |f| %>
<%= f.label "Tytuł wiadomości" %><br>
<%= f.text_field :title %><br>
<%= f.label "Treść wiadomości" %><br>
<%= f.text_area :content %><br>
<%= f.submit "Zapisz" %>
<% end %>

app/views/messages/index.html.erb
<h1>Tu będzie index</h1><br>
<%= link_to "Nowa", new_message_path %><br>

<% @messages.each do |message| %>
	<h3><%= link_to message.title, message %></h3>
	<%= message.content %><br>
	<%= message.created_at %><br>
	<% end %>

app/views/messages/new.html.erb
<h1>Tu dodasz nową</h1><br>
<%= form_for(@message) do |f| %>
<%= f.label "Tytuł wiadomości" %><br>
<%= f.text_field :title %><br>
<%= f.label "Treść wiadomości" %><br>
<%= f.text_area :content %><br>
<%= f.submit "Zapisz" %>
<% end %>

app/views/messages/show.html.erb
<h2><%= @message.title %></h2>
<p><%= @message.content %></p>
<%= link_to "Edytuj", edit_message_path(@message) %>
<%= link_to "Usuń", message_path(@message), method: :delete, data: { confirm: 'Na pewno?' } %>